### ISSUE TITLE
Cors issue on api call

### ISSUE THREAD

**Issue by anandmainali5** [EscolaLMS/Front#499]
Can you update the readme file to setup the frontend & connect it with docker backend of Wellms api??

I tried to setup but i'm getting below error on frontend:

<img width="1512" alt="Screenshot 2024-09-30 at 9 07 51 AM" src="https://github.com/user-attachments/assets/a02802fc-2d79-4c6a-8077-d20fbe8483d2">

**Comment by qunabu** [comment]
Actually I'm working on this, there will be update this week

**Comment by anandmainali5** [comment]
thanks. :)

**Comment by anandmainali5** [comment]
@qunabu any update on this??


Also, i saw some changes in [API](https://github.com/EscolaLMS/API) and tried to use that.. but the docker is updated for ```develop``` only.
And i can't use develop version with docker in ```Create-LMS-App``` as it always replaces ```develop``` with ```latest``` when i ever i try to run the docker.

**Comment by qunabu** [comment]
We have pushed big update yesterday, after QA today I'll let you know

Both docker tags develop and latest are updated now 

Can you try 'docker compose pull' ?
You might have to refresh with 'make refresh ' but beware this is deleting previous persistent data

**Comment by anandmainali5** [comment]
tried with latest update still the cors issue is not resolved..

**Comment by anandmainali5** [comment]
@qunabu any update on this?

**Comment by qunabu** [comment]
Can you write to me at mateusz@eacolasoft.com we can schedule a call an I could help you during live session?
